title: Will Napolini
email: your-email@example.com
description: 'Mindset • Skillset • Toolset'
baseurl: '/willbio.github.io'
url: 'https://github.com/WillEasyStart/willbio.github.io' # the base hostname & protocol for your site, e.g. http://example.com
repository: 'WillEasyStart/willbio.github.io'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/
  shop_items:
    output: true
    permalink: /shop/:title/

# Default values for posts
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'Will Napolini'
      image: '/assets/images/default-blog-image.jpg'
  - scope:
      path: ''
      type: 'shop_items'
    values:
      layout: 'shop-item'
      image: '/assets/images/default-shop-image.jpg'

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - todo.md

# SEO Tag settings
seo_tag:
  image: /assets/icons/icon-512x512.png
  twitter:
    username: willnapolini
  social:
    name: Will Napolini
    links:
      - https://twitter.com/willnapolini
      - https://github.com/willnapolini
      - https://instagram.com/willnapolini
      - https://t.me/willnapolini

# PWA settings
service_worker:
  src: /sw.js
  scope: /

# Custom variables (for use in layouts)
author_avatar: 'https://avatars.githubusercontent.com/u/192521042?v=4'
